version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - postgres
    command: -url=jdbc:postgresql://postgres/localdb -user=myuser -password=mypassword migrate
    volumes:
      - ./flyway/sql:/flyway/sql

volumes:
  postgres_data: