version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Operational
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - postgres
    command: -url=jdbc:postgresql://postgres/Operational -user=root -password=rootpassword migrate
    volumes:
      - ./flyway/sql:/flyway/sql

volumes:
  postgres_data: