version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: "exit 0"
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:latest
    depends_on:
      postgres:
        condition: service_healthy
    command: -url=jdbc:postgresql://postgres/localdb -user=myuser -password=mypassword migrate
    volumes:
      - ./flyway/sql:/flyway/sql

volumes:
  postgres_data: